import Foundation

/// The shipped detection rules.
///
/// Patterns deliberately avoid `\b`: in ICU, CJK characters count as word
/// characters, so `\b\d{11}\b` never matches "手机13812345678". Explicit
/// look-arounds are used instead.
public enum BuiltinRules {
    public static let all: [SensitiveRule] = [
        // MARK: Phone numbers
        SensitiveRule(id: "phone.cn.mobile",
                      category: .phoneNumber,
                      pattern: "(?<![0-9])1[3-9][0-9]([ \\-]?[0-9]{4}){2}(?![0-9])",
                      baseConfidence: 0.88,
                      contextKeywords: ContextKeywords.phoneNumber,
                      contextBoost: 0.1,
                      validate: { SensitiveValidators.isValidChinaMobile($0) }),
        SensitiveRule(id: "phone.cn.mobile.international",
                      category: .phoneNumber,
                      pattern: "(?:\\+?86[ \\-]?)1[3-9][0-9]{9}(?![0-9])",
                      baseConfidence: 0.9,
                      contextKeywords: ContextKeywords.phoneNumber,
                      validate: { SensitiveValidators.isValidChinaMobile($0) }),
        SensitiveRule(id: "phone.cn.landline",
                      category: .phoneNumber,
                      pattern: "(?<![0-9])0[1-9][0-9]{1,2}[ \\-]?[2-9][0-9]{6,7}(?![0-9])",
                      baseConfidence: 0.72,
                      contextKeywords: ContextKeywords.phoneNumber,
                      contextBoost: 0.2),
        SensitiveRule(id: "phone.masked.tail",
                      category: .phoneNumber,
                      pattern: "(?<![0-9])1[3-9][0-9]\\*{4}[0-9]{4}(?![0-9])",
                      baseConfidence: 0.6,
                      contextKeywords: ContextKeywords.phoneNumber,
                      isEnabledByDefault: false),

        // MARK: Identity documents
        SensitiveRule(id: "id.cn.resident18",
                      category: .idCard,
                      pattern: "(?<![0-9Xx])[1-9][0-9]{5}(?:19|20)[0-9]{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12][0-9]|3[01])[0-9]{3}[0-9Xx](?![0-9Xx])",
                      baseConfidence: 0.95,
                      contextKeywords: ContextKeywords.idCard,
                      contextBoost: 0.05,
                      validate: { SensitiveValidators.isValidChinaID($0) }),
        SensitiveRule(id: "id.cn.resident15",
                      category: .idCard,
                      pattern: "(?<![0-9])[1-9][0-9]{5}[0-9]{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12][0-9]|3[01])[0-9]{3}(?![0-9])",
                      baseConfidence: 0.8,
                      contextKeywords: ContextKeywords.idCard,
                      contextBoost: 0.15,
                      validate: { SensitiveValidators.isValidLegacyChinaID($0) }),
        SensitiveRule(id: "id.passport",
                      category: .passport,
                      pattern: "(?<![A-Za-z0-9])[EeGgDdSsPp][A-Za-z]?[0-9]{7,8}(?![A-Za-z0-9])",
                      baseConfidence: 0.55,
                      contextKeywords: ContextKeywords.passport,
                      contextBoost: 0.35,
                      requiresContext: true),
        SensitiveRule(id: "id.hkmacau.permit",
                      category: .passport,
                      pattern: "(?<![A-Za-z0-9])[CcWw][0-9]{8}(?![A-Za-z0-9])",
                      baseConfidence: 0.5,
                      contextKeywords: ContextKeywords.passport,
                      contextBoost: 0.4,
                      requiresContext: true),

        // MARK: Bank cards and accounts
        SensitiveRule(id: "bank.card",
                      category: .bankCard,
                      pattern: "(?<![0-9])(?:[0-9]{4}[ \\-]?){3}[0-9]{1,7}(?![0-9])",
                      baseConfidence: 0.9,
                      contextKeywords: ContextKeywords.bankCard,
                      contextBoost: 0.1,
                      validate: { SensitiveValidators.isPlausibleBankCard($0) }),
        SensitiveRule(id: "bank.account.context",
                      category: .bankCard,
                      pattern: "(?<![0-9])[0-9]{12,22}(?![0-9])",
                      baseConfidence: 0.5,
                      contextKeywords: ContextKeywords.bankCard,
                      contextBoost: 0.4,
                      requiresContext: true),
        SensitiveRule(id: "bank.cvv",
                      category: .credential,
                      pattern: "(?i)(?:cvv|cvc|安全码)[^0-9]{0,6}([0-9]{3,4})(?![0-9])",
                      captureGroup: 1,
                      baseConfidence: 0.9),

        // MARK: Contact details
        SensitiveRule(id: "email.address",
                      category: .email,
                      pattern: "[A-Za-z0-9._%+\\-]+@[A-Za-z0-9\\-]+(?:\\.[A-Za-z0-9\\-]+)+",
                      baseConfidence: 0.93),
        SensitiveRule(id: "social.wechat",
                      category: .socialAccount,
                      pattern: "(?i)(?:微信号?|wechat|wxid)[：:\\s]{0,4}([A-Za-z][A-Za-z0-9_\\-]{5,19})",
                      captureGroup: 1,
                      baseConfidence: 0.85),
        SensitiveRule(id: "social.qq",
                      category: .socialAccount,
                      pattern: "(?i)(?:qq号?|扣扣)[：:\\s]{0,4}([1-9][0-9]{4,10})(?![0-9])",
                      captureGroup: 1,
                      baseConfidence: 0.85),

        // MARK: Names and addresses
        SensitiveRule(id: "name.cn",
                      category: .personName,
                      pattern: "(?<![\\u4e00-\\u9fa5])(?:赵|钱|孙|李|周|吴|郑|王|冯|陈|褚|卫|蒋|沈|韩|杨|朱|秦|尤|许|何|吕|施|张|孔|曹|严|华|金|魏|陶|姜|戚|谢|邹|喻|柏|水|窦|章|云|苏|潘|葛|奚|范|彭|郎|鲁|韦|昌|马|苗|凤|花|方|俞|任|袁|柳|唐|罗|薛|雷|贺|倪|汤|殷|罗|毕|郝|邬|安|常|乐|于|时|傅|皮|齐|康|伍|余|元|卜|顾|孟|平|黄|和|穆|萧|尹|姚|邵|湛|汪|祁|毛|禹|狄|米|贝|明|臧|计|伏|成|戴|谈|宋|茅|庞|熊|纪|舒|屈|项|祝|董|梁|杜|阮|蓝|闵|席|季|麻|强|贾|路|娄|危|江|童|颜|郭|梅|盛|林|刁|钟|徐|邱|骆|高|夏|蔡|田|樊|胡|凌|霍|虞|万|支|柯|昝|管|卢|莫|房|裘|缪|干|解|应|宗|丁|宣|贲|邓|郁|单|杭|洪|包|诸|左|石|崔|吉|钮|龚|程|嵇|邢|滑|裴|陆|荣|翁|荀|羊|於|惠|甄|曲|封|芮|羿|储|靳|汲|邴|糜|松|井|段|富|巫|乌|焦|巴|弓|牧|隗|山|谷|车|侯|宓|蓬|全|郗|班|仰|秋|仲|伊|宫|宁|仇|栾|暴|甘|钭|厉|戎|祖|武|符|刘|景|詹|束|龙|叶|幸|司|韶|郜|黎|蓟|薄|印|宿|白|怀|蒲|邰|从|鄂|索|咸|籍|赖|卓|蔺|屠|蒙|池|乔|阴|欧|夔|隆|师|巩|厍|聂|晁|勾|敖|融|冷|訾|辛|阚|那|简|饶|空|曾|毋|沙|乜|养|鞠|须|丰|巢|关|蒯|相|查|後|荆|红|游|竺|权|逯|盖|益|桓|公)[\\u4e00-\\u9fa5]{1,3}(?![\\u4e00-\\u9fa5])",
                      baseConfidence: 0.42,
                      contextKeywords: ContextKeywords.personName,
                      contextBoost: 0.4),
        SensitiveRule(id: "name.cn.masked",
                      category: .personName,
                      pattern: "(?<![\\u4e00-\\u9fa5])[\\u4e00-\\u9fa5][*\\u2217]{1,2}(?![\\u4e00-\\u9fa5])",
                      baseConfidence: 0.3,
                      contextKeywords: ContextKeywords.personName,
                      contextBoost: 0.3,
                      isEnabledByDefault: false),
        SensitiveRule(id: "address.cn.detailed",
                      category: .address,
                      pattern: "[\\u4e00-\\u9fa5]{2,10}(?:省|自治区|特别行政区|市)[\\u4e00-\\u9fa5]{2,12}(?:市|区|县|镇|乡|旗)[\\u4e00-\\u9fa50-9A-Za-z]{2,30}(?:路|街|道|巷|弄|号|小区|花园|大厦|广场|苑|村|栋|单元|室|层|楼)[\\u4e00-\\u9fa50-9A-Za-z\\-]{0,20}",
                      baseConfidence: 0.78,
                      contextKeywords: ContextKeywords.address,
                      contextBoost: 0.15),
        SensitiveRule(id: "address.cn.street",
                      category: .address,
                      pattern: "[\\u4e00-\\u9fa5]{2,12}(?:路|街|道|巷|弄)[0-9]{1,5}号(?:[\\u4e00-\\u9fa50-9]{0,12}(?:栋|单元|室|层|楼))?",
                      baseConfidence: 0.55,
                      contextKeywords: ContextKeywords.address,
                      contextBoost: 0.35),

        // MARK: Vehicles
        SensitiveRule(id: "plate.cn",
                      category: .plateNumber,
                      pattern: "(?<![A-Za-z0-9])[京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领]{1}[A-HJ-NP-Z]{1}(?:[A-HJ-NP-Z0-9]{5}|[0-9]{5}[DF]|[DF][A-HJ-NP-Z0-9][0-9]{4})(?![A-Za-z0-9])",
                      baseConfidence: 0.86,
                      contextKeywords: ContextKeywords.plateNumber),
        SensitiveRule(id: "vehicle.vin",
                      category: .vehicleIdentification,
                      pattern: "(?<![A-Za-z0-9])[A-HJ-NPR-Z0-9]{17}(?![A-Za-z0-9])",
                      baseConfidence: 0.7,
                      contextKeywords: ContextKeywords.vehicleIdentification,
                      contextBoost: 0.25,
                      validate: { SensitiveValidators.isValidVIN($0) }),

        // MARK: Codes, money, logistics
        SensitiveRule(id: "code.verification",
                      category: .verificationCode,
                      pattern: "(?i)(?:验证码|校验码|动态码|动态密码|短信码|code|otp)[^0-9]{0,8}([0-9]{4,8})(?![0-9])",
                      captureGroup: 1,
                      baseConfidence: 0.95),
        SensitiveRule(id: "amount.with.context",
                      category: .amount,
                      pattern: "(?:[¥￥$]|CNY|RMB)?\\s?[0-9]{1,3}(?:,[0-9]{3})+(?:\\.[0-9]{1,2})?|(?:[¥￥$])\\s?[0-9]+(?:\\.[0-9]{1,2})?",
                      baseConfidence: 0.4,
                      contextKeywords: ContextKeywords.amount,
                      contextBoost: 0.45,
                      requiresContext: true),
        SensitiveRule(id: "logistics.tracking.carrier",
                      category: .trackingNumber,
                      pattern: "(?i)(?:SF|JD|YT|ZTO|STO|JT|YD|HTKY|EMS)[0-9]{10,18}(?![0-9])",
                      baseConfidence: 0.85),
        SensitiveRule(id: "logistics.tracking.context",
                      category: .trackingNumber,
                      pattern: "(?<![0-9])[0-9]{10,20}(?![0-9])",
                      baseConfidence: 0.4,
                      contextKeywords: ContextKeywords.trackingNumber,
                      contextBoost: 0.45,
                      requiresContext: true),
        SensitiveRule(id: "membership.number",
                      category: .custom,
                      pattern: "(?<![0-9A-Za-z])[0-9A-Za-z]{6,20}(?![0-9A-Za-z])",
                      baseConfidence: 0.35,
                      contextKeywords: ContextKeywords.membership,
                      contextBoost: 0.45,
                      requiresContext: true,
                      isEnabledByDefault: false),

        // MARK: Dates
        SensitiveRule(id: "date.birth",
                      category: .birthDate,
                      pattern: "(?:19|20)[0-9]{2}[\\-/年](?:0?[1-9]|1[0-2])[\\-/月](?:0?[1-9]|[12][0-9]|3[01])日?",
                      baseConfidence: 0.45,
                      contextKeywords: ContextKeywords.birthDate,
                      contextBoost: 0.4),

        // MARK: Network
        SensitiveRule(id: "network.ipv4",
                      category: .ipAddress,
                      pattern: "(?<![0-9.])(?:(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(?![0-9.])",
                      baseConfidence: 0.8),
        SensitiveRule(id: "network.mac",
                      category: .ipAddress,
                      pattern: "(?<![0-9A-Fa-f:])(?:[0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}(?![0-9A-Fa-f:])",
                      baseConfidence: 0.85),
        SensitiveRule(id: "network.url",
                      category: .webAddress,
                      pattern: "(?i)(?:https?://|www\\.)[A-Za-z0-9\\-._~:/?#\\[\\]@!$&'()*+,;=%]{4,}",
                      baseConfidence: 0.6),

        // MARK: Secrets
        SensitiveRule(id: "secret.openai",
                      category: .credential,
                      pattern: "sk-[A-Za-z0-9_\\-]{16,}",
                      baseConfidence: 0.98),
        SensitiveRule(id: "secret.github",
                      category: .credential,
                      pattern: "gh[pousr]_[A-Za-z0-9]{16,}",
                      baseConfidence: 0.98),
        SensitiveRule(id: "secret.aws",
                      category: .credential,
                      pattern: "(?:AKIA|ASIA)[0-9A-Z]{12,}",
                      baseConfidence: 0.98),
        SensitiveRule(id: "secret.jwt",
                      category: .credential,
                      pattern: "eyJ[A-Za-z0-9_\\-]{8,}\\.[A-Za-z0-9_\\-]{8,}\\.[A-Za-z0-9_\\-]{4,}",
                      baseConfidence: 0.97),
        SensitiveRule(id: "secret.bearer",
                      category: .credential,
                      pattern: "(?i)bearer\\s+([A-Za-z0-9._\\-]{16,})",
                      captureGroup: 1,
                      baseConfidence: 0.95),
        SensitiveRule(id: "secret.private.key",
                      category: .credential,
                      pattern: "-----BEGIN [A-Z ]*PRIVATE KEY-----",
                      baseConfidence: 0.99),
        SensitiveRule(id: "secret.long.hex",
                      category: .credential,
                      pattern: "(?<![A-Fa-f0-9])[A-Fa-f0-9]{32,}(?![A-Fa-f0-9])",
                      baseConfidence: 0.6,
                      contextKeywords: ContextKeywords.credential,
                      contextBoost: 0.3),
        SensitiveRule(id: "secret.labelled",
                      category: .credential,
                      pattern: "(?i)(?:密码|口令|密钥|token|secret|password|passwd|api[ _\\-]?key)[：:=\\s]{1,4}([A-Za-z0-9!@#$%^&*_\\-+.]{6,})",
                      captureGroup: 1,
                      baseConfidence: 0.9)
    ]

    public static func rules(for categories: Set<SensitiveCategory>) -> [SensitiveRule] {
        all.filter { categories.contains($0.category) }
    }

    public static var defaultEnabledCategories: Set<SensitiveCategory> {
        Set(SensitiveCategory.allCases.filter(\.isEnabledByDefault))
    }
}
